REM district_arcology_housing.dds
REM district_arcology_housing_big.dds
REM district_arcology_hightech.dds
REM district_arcology_hightech_big.dds
REM district_arcology_industry.dds
REM district_arcology_industry_big.dds
REM district_arcology_support.dds
REM district_arcology_support_big.dds
REM district_arcology_spaceport.dds
REM district_arcology_spaceport_big.dds
REM district_habitat_commercial.dds
REM district_habitat_commercial_big.dds
REM district_habitat_cultural.dds
REM district_habitat_cultural_big.dds
REM district_habitat_science.dds
REM district_habitat_science_big.dds
REM district_planet_all_city.dds
REM district_planet_all_city_big.dds
REM district_planet_adv_farming.dds
REM district_planet_adv_farming_big.dds
REM district_planet_adv_generator.dds
REM district_planet_adv_generator_big.dds
REM district_planet_adv_mining.dds
REM district_planet_adv_mining_big.dds
REM district_planet_rur_industrial.dds
REM district_planet_rur_industrial_big.dds
REM district_planet_spc_bunker.dds
REM district_planet_spc_bunker_big.dds

copy district_arcology_spaceport.dds district_arcology_archeology.dds
copy district_arcology_spaceport_big.dds district_arcology_archeology_big.dds
copy district_arcology_spaceport.dds district_arcology_assembly.dds
copy district_arcology_spaceport_big.dds district_arcology_assembly_big.dds
copy district_arcology_spaceport.dds district_arcology_cloning.dds
copy district_arcology_spaceport_big.dds district_arcology_cloning_big.dds
copy district_arcology_spaceport.dds district_arcology_commerce.dds
copy district_arcology_spaceport_big.dds district_arcology_commerce_big.dds
copy district_arcology_housing.dds district_arcology_hive.dds
copy district_arcology_housing_big.dds district_arcology_hive_big.dds
copy district_arcology_housing.dds district_arcology_nexus.dds
copy district_arcology_housing_big.dds district_arcology_nexus_big.dds
copy district_arcology_spaceport.dds district_arcology_stronghold.dds
copy district_arcology_spaceport_big.dds district_arcology_stronghold_big.dds
copy district_planet_rur_industrial.dds district_habitat_collector.dds
copy district_planet_rur_industrial_big.dds district_habitat_collector_big.dds
copy district_planet_rur_industrial.dds district_habitat_factory.dds
copy district_planet_rur_industrial_big.dds district_habitat_factory_big.dds
copy district_planet_adv_farming.dds district_habitat_farming.dds
copy district_planet_adv_farming_big.dds district_habitat_farming_big.dds
copy district_planet_adv_generator.dds district_habitat_generator.dds
copy district_planet_adv_generator_big.dds district_habitat_generator_big.dds
copy district_planet_all_city.dds district_habitat_housing.dds
copy district_planet_all_city_big.dds district_habitat_housing_big.dds
copy district_habitat_science.dds district_habitat_intelligence.dds
copy district_habitat_science_big.dds district_habitat_intelligence_big.dds
copy district_habitat_commercial.dds district_habitat_maintanance.dds
copy district_habitat_commercial_big.dds district_habitat_maintanance_big.dds
copy district_planet_adv_mining.dds district_habitat_mining.dds
copy district_planet_adv_mining_big.dds district_habitat_mining_big.dds
copy district_habitat_cultural.dds district_habitat_network.dds
copy district_habitat_cultural_big.dds district_habitat_network_big.dds
copy district_habitat_science.dds district_habitat_outpost.dds
copy district_habitat_science_big.dds district_habitat_outpost_big.dds
copy district_planet_rur_industrial.dds district_habitat_smelter.dds
copy district_planet_rur_industrial_big.dds district_habitat_smelter_big.dds
copy district_planet_all_city.dds district_planet_all_hive.dds
copy district_planet_all_city_big.dds district_planet_all_hive_big.dds
copy district_planet_all_city.dds district_planet_all_nexus.dds
copy district_planet_all_city_big.dds district_planet_all_nexus_big.dds
copy district_planet_rur_industrial.dds district_planet_hst_crystal.dds
copy district_planet_rur_industrial_big.dds district_planet_hst_crystal_big.dds
copy district_planet_rur_industrial.dds district_planet_hst_exogas.dds
copy district_planet_rur_industrial_big.dds district_planet_hst_exogas_big.dds
copy district_habitat_science.dds district_planet_hst_frozen.dds
copy district_habitat_science_big.dds district_planet_hst_frozen_big.dds
copy district_habitat_science.dds district_planet_hst_hazard.dds
copy district_habitat_science_big.dds district_planet_hst_hazard_big.dds
copy district_planet_rur_industrial.dds district_planet_hst_motes.dds
copy district_planet_rur_industrial_big.dds district_planet_hst_motes_big.dds
copy district_habitat_science.dds district_planet_hst_thermal.dds
copy district_habitat_science_big.dds district_planet_hst_thermal_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_alpine.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_alpine_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_arctic.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_arctic_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_arid.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_arid_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_continental.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_continental_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_desert.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_desert_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_ocean.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_ocean_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_savannah.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_savannah_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_tropical.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_tropical_big.dds
copy district_planet_rur_industrial.dds district_planet_ind_tundra.dds
copy district_planet_rur_industrial_big.dds district_planet_ind_tundra_big.dds
copy district_planet_adv_farming.dds district_planet_rur_farming.dds
copy district_planet_adv_farming_big.dds district_planet_rur_farming_big.dds
copy district_planet_adv_generator.dds district_planet_rur_generator.dds
copy district_planet_adv_generator_big.dds district_planet_rur_generator_big.dds
copy district_planet_adv_mining.dds district_planet_rur_mining.dds
copy district_planet_adv_mining_big.dds district_planet_rur_mining_big.dds
copy district_planet_spc_bunker.dds district_planet_spc_defenses.dds
copy district_planet_spc_bunker_big.dds district_planet_spc_defenses_big.dds
copy district_planet_spc_bunker.dds district_planet_spc_incubator.dds
copy district_planet_spc_bunker_big.dds district_planet_spc_incubator_big.dds
copy district_planet_spc_bunker.dds district_planet_spc_nanites.dds
copy district_planet_spc_bunker_big.dds district_planet_spc_nanites_big.dds
copy district_planet_spc_bunker.dds district_planet_spc_psionic.dds
copy district_planet_spc_bunker_big.dds district_planet_spc_psionic_big.dds
copy district_planet_spc_bunker.dds district_planet_spc_spice.dds
copy district_planet_spc_bunker_big.dds district_planet_spc_spice_big.dds