del district_arcology_archeology.dds
del district_arcology_archeology_big.dds
del district_arcology_assembly.dds
del district_arcology_assembly_big.dds
del district_arcology_cloning.dds
del district_arcology_cloning_big.dds
del district_arcology_commerce.dds
del district_arcology_commerce_big.dds
del district_arcology_hive.dds
del district_arcology_hive_big.dds
del district_arcology_nexus.dds
del district_arcology_nexus_big.dds
del district_arcology_stronghold.dds
del district_arcology_stronghold_big.dds
del district_habitat_collector.dds
del district_habitat_collector_big.dds
del district_habitat_factory.dds
del district_habitat_factory_big.dds
del district_habitat_farming.dds
del district_habitat_farming_big.dds
del district_habitat_generator.dds
del district_habitat_generator_big.dds
del district_habitat_housing.dds
del district_habitat_housing_big.dds
del district_habitat_intelligence.dds
del district_habitat_intelligence_big.dds
del district_habitat_maintanance.dds
del district_habitat_maintanance_big.dds
del district_habitat_mining.dds
del district_habitat_mining_big.dds
del district_habitat_network.dds
del district_habitat_network_big.dds
del district_habitat_outpost.dds
del district_habitat_outpost_big.dds
del district_habitat_smelter.dds
del district_habitat_smelter_big.dds
del district_planet_all_hive.dds
del district_planet_all_hive_big.dds
del district_planet_all_nexus.dds
del district_planet_all_nexus_big.dds
del district_planet_hst_crystal.dds
del district_planet_hst_crystal_big.dds
del district_planet_hst_exogas.dds
del district_planet_hst_exogas_big.dds
del district_planet_hst_frozen.dds
del district_planet_hst_frozen_big.dds
del district_planet_hst_hazard.dds
del district_planet_hst_hazard_big.dds
del district_planet_hst_motes.dds
del district_planet_hst_motes_big.dds
del district_planet_hst_thermal.dds
del district_planet_hst_thermal_big.dds
del district_planet_ind_alpine.dds
del district_planet_ind_alpine_big.dds
del district_planet_ind_arctic.dds
del district_planet_ind_arctic_big.dds
del district_planet_ind_arid.dds
del district_planet_ind_arid_big.dds
del district_planet_ind_continental.dds
del district_planet_ind_continental_big.dds
del district_planet_ind_desert.dds
del district_planet_ind_desert_big.dds
del district_planet_ind_ocean.dds
del district_planet_ind_ocean_big.dds
del district_planet_ind_savannah.dds
del district_planet_ind_savannah_big.dds
del district_planet_ind_tropical.dds
del district_planet_ind_tropical_big.dds
del district_planet_ind_tundra.dds
del district_planet_ind_tundra_big.dds
del district_planet_rur_farming.dds
del district_planet_rur_farming_big.dds
del district_planet_rur_generator.dds
del district_planet_rur_generator_big.dds
del district_planet_rur_mining.dds
del district_planet_rur_mining_big.dds
del district_planet_spc_defenses.dds
del district_planet_spc_defenses_big.dds
del district_planet_spc_incubator.dds
del district_planet_spc_incubator_big.dds
del district_planet_spc_nanites.dds
del district_planet_spc_nanites_big.dds
del district_planet_spc_psionic.dds
del district_planet_spc_psionic_big.dds
del district_planet_spc_spice.dds
del district_planet_spc_spice_big.dds