del district_arcology_arms_industry.dds
del district_arcology_arms_industry_big.dds
del district_arcology_civilian_industry.dds
del district_arcology_civilian_industry_big.dds
del district_arcology_industrial.dds
del district_arcology_industrial_big.dds
del district_arcology_leisure.dds
del district_arcology_leisure_big.dds
del district_city.dds
del district_city_big.dds
del district_farming.dds
del district_farming_big.dds
del district_generator.dds
del district_generator_big.dds
del district_hab_commercial.dds
del district_hab_commercial_big.dds
del district_hab_cultural.dds
del district_hab_cultural_big.dds
del district_hab_energy.dds
del district_hab_energy_big.dds
del district_hab_housing.dds
del district_hab_housing_big.dds
del district_hab_industrial.dds
del district_hab_industrial_big.dds
del district_hab_mining.dds
del district_hab_mining_big.dds
del district_hab_science.dds
del district_hab_science_big.dds
del district_hive.dds
del district_hive_big.dds
del district_industrial.dds
del district_industrial_big.dds
del district_mining.dds
del district_mining_big.dds
del district_nexus.dds
del district_nexus_big.dds
del district_research.dds
del district_research_big.dds
del district_rw_city.dds
del district_rw_city_big.dds
del district_rw_commercial.dds
del district_rw_commercial_big.dds
del district_rw_farming.dds
del district_rw_farming_big.dds
del district_rw_generator.dds
del district_rw_generator_big.dds
del district_rw_hive.dds
del district_rw_hive_big.dds
del district_rw_industrial.dds
del district_rw_industrial_big.dds
del district_rw_nexus.dds
del district_rw_nexus_big.dds
del district_rw_science.dds
del district_rw_science_big.dds